"""add comment table_2

Revision ID: 5394f90a5302
Revises: d8f9fe2565f1
Create Date: 2021-03-01 17:35:10.383040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5394f90a5302'
down_revision = 'd8f9fe2565f1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
