"""add comment table 3

Revision ID: 59b9b4ea798c
Revises: 5394f90a5302
Create Date: 2021-03-01 17:35:25.380524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b9b4ea798c'
down_revision = '5394f90a5302'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
