"""add comment table

Revision ID: d8f9fe2565f1
Revises: d4d4faeecfbf
Create Date: 2021-03-01 17:32:35.649695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f9fe2565f1'
down_revision = 'd4d4faeecfbf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
